# Generated by Django 4.2.5 on 2024-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
