# Generated by Django 4.2.5 on 2024-03-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_user', '0002_user_info_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='education',
        ),
    ]
