# Generated by Django 4.2.5 on 2024-03-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_v_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
